application: your-project-id
version: 1
runtime: php
api_version: 1

handlers:
- url: /(.*\.(htm|html|css|js))$
  static_files: public.built/\1
  upload: public.built/.*\.(htm|html|css|js)$
  application_readable: true

- url: /wp-content/(.*\.(ico|jpg|png|gif))$
  static_files: public.built/wp-content/\1
  upload: public.built/wp-content/.*\.(ico|jpg|png|gif)$
  application_readable: true

- url: /(.*\.(ico|jpg|png|gif))$
  static_files: public.built/\1
  upload: public.built/.*\.(ico|jpg|png|gif)$
  application_readable: true

- url: /wp-admin/(.+)
  script: public.built/wp-admin/\1
  secure: always

- url: /wp-admin/
  script: public.built/wp-admin/index.php
  secure: always

- url: /wp-login.php
  script: public.built/wp-login.php
  secure: always

- url: /wp-cron.php
  script: public.built/wp-cron.php
  login: admin

- url: /xmlrpc.php
  script: public.built/xmlrpc.php

- url: /wp-(.+).php
  script: public.built/wp-\1.php

- url: /(.+)?/?
  script: public.built/index.php

skip_files:
- ^(.*/)?\.zip$
- ^(.*/)?\.bat$
- ^(.*/)?\.sh$
- ^(.*/)?\.md$
